# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ota_metafiles.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ota_metafiles.proto\x12\totaclient\"\x9a\x01\n\nRegularInf\x12\x0c\n\x04mode\x18\x01 \x01(\x05\x12\x0b\n\x03uid\x18\x02 \x01(\x05\x12\x0b\n\x03gid\x18\x03 \x01(\x05\x12\r\n\x05nlink\x18\x04 \x01(\x05\x12\x12\n\nsha256hash\x18\x05 \x01(\x0c\x12\x0c\n\x04path\x18\x06 \x01(\t\x12\x0c\n\x04size\x18\x07 \x01(\x03\x12\r\n\x05inode\x18\x08 \x01(\x03\x12\x16\n\x0e\x63ompressed_alg\x18\t \x01(\t\"D\n\x0c\x44irectoryInf\x12\x0c\n\x04mode\x18\x01 \x01(\x05\x12\x0b\n\x03uid\x18\x02 \x01(\x05\x12\x0b\n\x03gid\x18\x03 \x01(\x05\x12\x0c\n\x04path\x18\x04 \x01(\t\"Y\n\x0fSymbolicLinkInf\x12\x0c\n\x04mode\x18\x01 \x01(\x05\x12\x0b\n\x03uid\x18\x02 \x01(\x05\x12\x0b\n\x03gid\x18\x03 \x01(\x05\x12\r\n\x05slink\x18\x04 \x01(\t\x12\x0f\n\x07srcpath\x18\x05 \x01(\t\"\x1d\n\rPersistentInf\x12\x0c\n\x04path\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ota_metafiles_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGULARINF._serialized_start=35
  _REGULARINF._serialized_end=189
  _DIRECTORYINF._serialized_start=191
  _DIRECTORYINF._serialized_end=259
  _SYMBOLICLINKINF._serialized_start=261
  _SYMBOLICLINKINF._serialized_end=350
  _PERSISTENTINF._serialized_start=352
  _PERSISTENTINF._serialized_end=381
# @@protoc_insertion_point(module_scope)
