from pathlib import Path


try:
    # version info is generated by setuptools-scm and stored in
    # otaclient._version, check pyproject.toml for settings
    from ._version import version as __version__, version_tuple
except ImportError:
    from otaclient.app.configs import EXTRA_VERSION_FILE

    # try import version from VERSION file if any
    _extra_version = Path(EXTRA_VERSION_FILE)
    if _extra_version.is_file():
        __version__ = _extra_version.read_text()
    else:
        __version__ = "unknown"
    version_tuple = (0, 0, "unknown")

__all__ = ["__version__", "version_tuple"]
