# Copyright 2022 TIER IV, INC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from pathlib import Path

# the package name for the otaclient package,
# in normal case it should be "otaclient"
otaclient_package_name = __name__.split(".")[0]

try:
    # version info is generated by setuptools-scm and stored in
    # otaclient._version, check pyproject.toml for settings
    from ._version import version as __version__, version_tuple
except ImportError:
    from otaclient.app.configs import EXTRA_VERSION_FILE

    # try import version from VERSION file if any
    _extra_version = Path(EXTRA_VERSION_FILE)
    if _extra_version.is_file():
        __version__ = _extra_version.read_text()
    else:
        __version__ = "unknown"
    version_tuple = (0, 0, "unknown")

__all__ = ["__version__", "version_tuple"]
