FROM ubuntu:20.04
ARG KERNEL_VERSION

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

# install all dependencies
RUN apt update && \
    apt install -y sudo ubuntu-minimal openssh-server && \
    apt install -y ubuntu-desktop-minimal --no-install-recommends && \
    apt install -y fonts-ubuntu && \
    apt install -y systemd-coredump vim git ansible && \
    apt install -y grub-efi-amd64 && \
    apt install -y linux-image-${KERNEL_VERSION} linux-headers-${KERNEL_VERSION} linux-modules-extra-${KERNEL_VERSION} && \
    apt install -y apt-utils python3-pip usbutils

# setup the image
RUN useradd -m autoware -s /bin/bash && \
    echo autoware:autoware | chpasswd && \
    gpasswd -a autoware sudo

WORKDIR /home/autoware

USER autoware