name: "Calculate Checksum"
description: "Calculates SHA256 checksums for specified file patterns"
inputs:
  file_patterns:
    description: "File patterns to calculate checksums for (space-separated)"
    required: true
    default: "*.{whl,squashfs,patch,json}"
  directory:
    description: "Directory containing the files"
    required: true
    default: "dist"

runs:
  using: "composite"
  steps:
    - name: Calculate checksum
      shell: bash
      run: |
        for FILE in ${{ inputs.directory }}/${{ inputs.file_patterns }}; do
          if [ -s ${FILE} ]; then
            sha256sum ${FILE} | sed -E "s@(\w+)\s+.*@sha256:\1@" > ${FILE}.checksum
            echo "Generated checksum for ${FILE}"
          fi
        done
