ecus:
- main: true # main ecu or not. only one ecu should be main.
  name: autoware # should be unique
  status: INITIALIZED # INITIALIZED | SUCCESS | FAILURE | UPDATING | NO_CONNECTION
  version: 123.456  # current version
  time_to_update: 40 # in second
  time_to_restart: 10 # in second

- name: perception1 # should be unique
  status: INITIALIZED # INITIALIZED | SUCCESS | FAILURE | UPDATING | NO_CONNECTION
  version: abc.def  # current version
  time_to_update: 60 # in second
  time_to_restart: 10 # in second

- name: perception2
  status: INITIALIZED # INITIALIZED | SUCCESS | FAILURE | UPDATING | NO_CONNECTION
  version: abc.def
  time_to_update: 60 # in second
  time_to_restart: 10 # in second

- name: perception3
  status: INITIALIZED # INITIALIZED | SUCCESS | FAILURE | UPDATING | NO_CONNECTION
  version: abc.def
  time_to_update: 60 # in second
  time_to_restart: 10 # in second

#- name: perception4
#  status: INITIALIZED # INITIALIZED | SUCCESS | FAILURE | UPDATING | NO_CONNECTION
#  version: abc.def
#  time_to_update: 60 # in second
#  time_to_restart: 10 # in second
