# ------ This file comes with otaclient image ------ #
# NOTE: total up to three DNS servers can be set here.

# If the host system use systemd-resolvd
nameserver 127.0.0.53

# other common public DNS
nameserver 1.1.1.1
nameserver 8.8.8.8