FROM base-image:latest

# prepare the repo
COPY ${REPO_LOCATION} /ota-client
# setup the permission
RUN chown -R autoware:autoware /ota-client

# install dependencies
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install -r /ota-client/app/requirements.txt && \
    python3 -m pip install -r /ota-client/e2e_tests/requirements.txt

WORKDIR /ota-client
USER autoware