ARG UBUNTU_BASE

FROM ghcr.io/tier4/ota-client/ota_img_for_test:ubuntu_22.04 AS ota_image

FROM ${UBUNTU_BASE}

ENV OTA_IMAGE_SERVER_ROOT="/ota-image"
ENV CERTS_DIR="/certs"

COPY --from=ota_image /${OTA_IMAGE_SERVER_ROOT} /
COPY --from=ota_image /${CERTS_DIR} /

# copy and setup the entry_point.sh
COPY ./docker/test_base/entry_point.sh /entry_point.sh

# bootstrapping the python environment
RUN set -eux; \
    apt-get update; \
    apt-get install -y -qq --no-install-recommends \
        python3.8 \
        python3-pip \
        git; \
    pip install -U pip; pip install uv; \
    chmod +x /entry_point.sh

ENTRYPOINT [ "/entry_point.sh" ]
