from pathlib import Path

try:
    # version info is generated by setuptools-scm and stored in
    # otaclient.app._version, check pyproject.toml for settings
    from ._version import version as __version__, version_tuple
except ImportError:
    # try import version from VERSION file if any
    version_file = Path(__file__).parent.parent / "version.txt"
    if version_file.is_file():
        __version__ = version_file.read_text()
    version_tuple = (0, 0, "unknown")

__all__ = ["__version__", "version_tuple"]
