# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from otaclient_api.v2 import otaclient_v2_pb2 as otaclient__api_dot_v2_dot_otaclient__v2__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in otaclient_api/v2/otaclient_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OtaClientServiceStub(object):
    """The OTA Client service definition.
    Style Guide: https://developers.google.com/protocol-buffers/docs/style#message_and_field_names
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Update = channel.unary_unary(
                '/OtaClientV2.OtaClientService/Update',
                request_serializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateRequest.SerializeToString,
                response_deserializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/OtaClientV2.OtaClientService/Abort',
                request_serializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.AbortRequest.SerializeToString,
                response_deserializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.AbortResponse.FromString,
                _registered_method=True)
        self.Rollback = channel.unary_unary(
                '/OtaClientV2.OtaClientService/Rollback',
                request_serializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.RollbackRequest.SerializeToString,
                response_deserializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.RollbackResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/OtaClientV2.OtaClientService/Status',
                request_serializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.StatusRequest.SerializeToString,
                response_deserializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ClientUpdate = channel.unary_unary(
                '/OtaClientV2.OtaClientService/ClientUpdate',
                request_serializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateRequest.SerializeToString,
                response_deserializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateResponse.FromString,
                _registered_method=True)


class OtaClientServiceServicer(object):
    """The OTA Client service definition.
    Style Guide: https://developers.google.com/protocol-buffers/docs/style#message_and_field_names
    """

    def Update(self, request, context):
        """
        `Update` service requests OTA client to start updating.
        The OTA client of each ECU retrieves the request that matches its own ECU
        id and starts it. Requests to each ECU included in the `UpdateRequest` are
        handled by that respective ECU and returns the response to the parent ECU.
        Main ECU merges the responses as UpdateResponse.
        After requesting `Update` and if the OTA status is `UPDATING`, the request is successful.
        Note that if the child ECU doesn't respond, the grandchild response is not
        included by `UpdateResponse`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """
        `Abort` service requests the OTA client to abort any currently running update operations.
        Each ECU attempts to halt its update process safely.
        The response indicates whether the abort command was accepted.
        If the update is in a critical zone, the abort command will be ignored.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """
        NOT YET
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """
        `Status` service requests OTA client to retrieve OTA client status.
        Note that if the child ECU doesn't respond, the grandchild response is not
        contained by `StatusResponse`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientUpdate(self, request, context):
        """
        `ClientUpdate` service requests OTA client to start client updating.
        The OTA client of each ECU retrieves the request that matches its own ECU
        id and starts it. Requests to each ECU included in the `UpdateRequest` are
        handled by that respective ECU and returns the response to the parent ECU.
        Main ECU merges the responses as UpdateResponse.
        After requesting `ClientUpdate` and if the OTA status is `CLIENT_UPDATING`,
        the request is successful. Note that if the child ECU doesn't respond, the
        grandchild response is not included by `UpdateResponse`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OtaClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateRequest.FromString,
                    response_serializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.AbortRequest.FromString,
                    response_serializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.AbortResponse.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.RollbackRequest.FromString,
                    response_serializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.RollbackResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.StatusRequest.FromString,
                    response_serializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.StatusResponse.SerializeToString,
            ),
            'ClientUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientUpdate,
                    request_deserializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateRequest.FromString,
                    response_serializer=otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OtaClientV2.OtaClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('OtaClientV2.OtaClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OtaClientService(object):
    """The OTA Client service definition.
    Style Guide: https://developers.google.com/protocol-buffers/docs/style#message_and_field_names
    """

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OtaClientV2.OtaClientService/Update',
            otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateRequest.SerializeToString,
            otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OtaClientV2.OtaClientService/Abort',
            otaclient__api_dot_v2_dot_otaclient__v2__pb2.AbortRequest.SerializeToString,
            otaclient__api_dot_v2_dot_otaclient__v2__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OtaClientV2.OtaClientService/Rollback',
            otaclient__api_dot_v2_dot_otaclient__v2__pb2.RollbackRequest.SerializeToString,
            otaclient__api_dot_v2_dot_otaclient__v2__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OtaClientV2.OtaClientService/Status',
            otaclient__api_dot_v2_dot_otaclient__v2__pb2.StatusRequest.SerializeToString,
            otaclient__api_dot_v2_dot_otaclient__v2__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OtaClientV2.OtaClientService/ClientUpdate',
            otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateRequest.SerializeToString,
            otaclient__api_dot_v2_dot_otaclient__v2__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
